// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'authResponseModel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AuthResponseModel _$AuthResponseModelFromJson(Map<String, dynamic> json) {
  return AuthResponseModel(
    json['empId'] as int,
    json['empDsc'] as String,
    json['companyId'] as int,
    json['empCatId'] as int,
    json['empTypeId'] as int,
    json['empDeptId'] as int,
    json['locId'] as int,
    json['empFname'] as String,
    json['empMname'] as String,
    json['empSname'] as String,
    json['empPhoto'] as String,
    json['empMobile1'] as String,
    json['empMobile2'] as String,
    json['empEmail'] as String,
    json['empAddressTemp'] as String,
    json['empAddressPerm'] as String,
    json['empBloodgrp'] as String,
    json['empEmergencyPerson1'] as String,
    json['empEmergencyNo1'] as String,
    json['empEmergencyPerson2'] as String,
    json['empEmergencyNo2'] as String,
    json['empRatePerhr'] as int,
    json['empJoiningDate'] as String,
    json['empPrevExpYrs'] as int,
    json['empPrevExpMonths'] as int,
    json['empLeavingDate'] as String,
    json['empLeavingReason'] as String,
    json['lockPeriod'] as String,
    json['termConditions'] as String,
    json['salaryId'] as int,
    json['delStatus'] as int,
    json['isActive'] as int,
    json['makerUserId'] as int,
    json['makerEnterDatetime'] as String,
    json['exInt1'] as int,
    json['exInt2'] as int,
    json['exInt3'] as int,
    json['exVar1'] as String,
    json['exVar2'] as String,
    json['exVar3'] as String,
    json['grossSalary'] as int,
    json['noOfHrs'] as int,
    json['gender'] as int,
    json['dob'] as String,
    json['scanCopy1'] as String,
    json['scanCopy2'] as String,
    json['pf'] as int,
    json['esic'] as int,
    json['bonus'] as int,
    json['cl'] as int,
    json['sl'] as int,
    json['pl'] as int,
  );
}

Map<String, dynamic> _$AuthResponseModelToJson(AuthResponseModel instance) =>
    <String, dynamic>{
      'empId': instance.empId,
      'empDsc': instance.empDsc,
      'companyId': instance.companyId,
      'empCatId': instance.empCatId,
      'empTypeId': instance.empTypeId,
      'empDeptId': instance.empDeptId,
      'locId': instance.locId,
      'empFname': instance.empFname,
      'empMname': instance.empMname,
      'empSname': instance.empSname,
      'empPhoto': instance.empPhoto,
      'empMobile1': instance.empMobile1,
      'empMobile2': instance.empMobile2,
      'empEmail': instance.empEmail,
      'empAddressTemp': instance.empAddressTemp,
      'empAddressPerm': instance.empAddressPerm,
      'empBloodgrp': instance.empBloodgrp,
      'empEmergencyPerson1': instance.empEmergencyPerson1,
      'empEmergencyNo1': instance.empEmergencyNo1,
      'empEmergencyPerson2': instance.empEmergencyPerson2,
      'empEmergencyNo2': instance.empEmergencyNo2,
      'empRatePerhr': instance.empRatePerhr,
      'empJoiningDate': instance.empJoiningDate,
      'empPrevExpYrs': instance.empPrevExpYrs,
      'empPrevExpMonths': instance.empPrevExpMonths,
      'empLeavingDate': instance.empLeavingDate,
      'empLeavingReason': instance.empLeavingReason,
      'lockPeriod': instance.lockPeriod,
      'termConditions': instance.termConditions,
      'salaryId': instance.salaryId,
      'delStatus': instance.delStatus,
      'isActive': instance.isActive,
      'makerUserId': instance.makerUserId,
      'makerEnterDatetime': instance.makerEnterDatetime,
      'exInt1': instance.exInt1,
      'exInt2': instance.exInt2,
      'exInt3': instance.exInt3,
      'exVar1': instance.exVar1,
      'exVar2': instance.exVar2,
      'exVar3': instance.exVar3,
      'grossSalary': instance.grossSalary,
      'noOfHrs': instance.noOfHrs,
      'gender': instance.gender,
      'dob': instance.dob,
      'scanCopy1': instance.scanCopy1,
      'scanCopy2': instance.scanCopy2,
      'pf': instance.pf,
      'esic': instance.esic,
      'bonus': instance.bonus,
      'cl': instance.cl,
      'sl': instance.sl,
      'pl': instance.pl,
    };
